// Derives cyber.generated.css from modern.css.
//
// The Modern skin is ~2900 lines with its palette written inline (gold
// hairlines, ember actions, obsidian panels). Cyber keeps Modern's layout and
// components and swaps the whole palette: navy room, ice-blue structure,
// blue→violet light. Rather than fork the sheet by hand (and drift), every
// warm value is mapped here and every rule is re-scoped one attribute deeper
// so it outranks the Modern rule it replaces. Re-run after editing modern.css:
//   node tauri/scripts/derive-cyber.mjs
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const src = path.join(here, "..", "src", "modern.css");
const out = path.join(here, "..", "src", "cyber.generated.css");

// rgb triplets (matched as "r, g, b" inside rgba())
const RGB = [
  // gold structure → ice blue
  ["200, 155, 94", "148, 170, 220"],
  ["232, 200, 147", "190, 205, 240"],
  ["226, 140, 80", "120, 140, 255"],
  // ember / heat → blue-violet light
  ["255, 106, 48", "109, 140, 255"],
  ["255, 150, 80", "140, 160, 255"],
  ["255, 160, 90", "140, 160, 255"],
  ["255, 170, 100", "160, 175, 255"],
  ["255, 140, 60", "110, 140, 255"],
  ["226, 102, 52", "99, 122, 250"],
  ["143, 29, 29", "67, 56, 202"],
  ["160, 43, 30", "220, 60, 80"],
  ["50, 12, 9", "20, 24, 60"],
  // warm text → cool text
  ["239, 227, 207", "229, 235, 247"],
  ["240, 227, 205", "229, 235, 247"],
  // warm whites (glass specular) → cool whites
  ["255, 246, 236", "236, 241, 255"],
  ["255, 240, 226", "236, 241, 255"],
  ["255, 236, 220", "236, 241, 255"],
  ["255, 240, 224", "226, 233, 252"],
  ["255, 248, 238", "240, 244, 255"],
  ["255, 210, 170", "170, 190, 255"],
  // obsidian panels → navy panels
  ["12, 10, 9", "11, 17, 32"],
  ["13, 11, 10", "13, 19, 36"],
  ["26, 19, 16", "22, 30, 56"],
  ["8, 7, 6", "7, 11, 20"],
];

const HEX = [
  ["#c89b5e", "#8ea6d6"], ["#e8c893", "#c7d6f5"], ["#d9ab6e", "#9db4e6"],
  ["#ff6a30", "#6d8cff"], ["#ffb24d", "#a78bfa"], ["#ffb083", "#b9c8ff"],
  ["#8f1d1d", "#4338ca"], ["#e26634", "#5b7cfa"], ["#ffcf9a", "#c4b5fd"],
  ["#e8bd83", "#b6c6ec"], ["#ffd7a6", "#dfe7ff"],
  ["#f3e6cf", "#eef2fb"], ["#f6ecda", "#f4f7fc"], ["#f0e3cd", "#e5ebf7"], ["#efe3cf", "#e5ebf7"],
  ["#5ec27a", "#34d399"], ["#a7d9b4", "#a7f3d0"], ["#c9564a", "#f87171"],
  ["#080706", "#070b14"], ["#0d0b0a", "#0b1120"], ["#131110", "#0f172a"], ["#0c0a09", "#0a0f1c"],
  ["#100e0c", "#0e1526"], ["#0a0908", "#0a0f1c"], ["#171311", "#151d33"],
  ["#1b1817", "#141c31"], ["#241d19", "#1b2445"], ["#0b0a09", "#0e1530"],
];

let css = readFileSync(src, "utf8");

// drop the header comment block and the font import (cyber.css carries its own)
css = css.replace(/^\/\*[\s\S]*?\*\/\s*/, "");
css = css.replace(/^@import url\([^)]*\);\s*/m, "");

for (const [from, to] of RGB) css = css.split(from).join(to);
for (const [from, to] of HEX) css = css.split(from).join(to).split(from.toUpperCase()).join(to);

// re-scope: one attribute deeper than Modern, so Cyber wins every tie
css = css.split('.ares[data-style="modern"]').join('.ares[data-style="modern"][data-surface="cyber"]');

const banner = `/* GENERATED by tauri/scripts/derive-cyber.mjs from modern.css — do not edit.
   Cyber = the Modern layout with the whole palette swapped to navy / ice-blue /
   blue→violet. Hand-written Cyber rules live in cyber.css, loaded after this. */
`;
writeFileSync(out, banner + css, "utf8");
console.log(`wrote ${path.relative(process.cwd(), out)} (${css.length} chars)`);
